import asyncio
import json
import os
import sys

backend_dir = os.path.dirname(os.path.abspath(__file__))
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

from app.services.llm.base import ChatMessage, ensure_chat_response, normalize_content_chunk
from app.services.llm.ollama_provider import OllamaProvider
from app.services.llm.external_providers import (
    AnthropicProvider,
    DeepSeekProvider,
    GeminiProvider,
    GroqProvider,
    MistralProvider,
    OpenAIProvider,
    OpenRouterProvider,
    QwenProvider,
)
from app.services.agent_service import AgentService, build_system_prompt
from app.services.tools.calculator import CalculatorTool
from app.services.tools.python_executor import PythonExecutorTool
from app.services.tools.shell_executor import ShellExecutorTool
from app.services.tools.http_request import HttpRequestTool
from app.services.project.generator import ProjectGenerator
from app.services.project.templates import TEMPLATES


def test_provider_chat_response_types():
    print("► STEP 4 — VERIFYING ALL LLM PROVIDERS RETURN STRING ChatResponse...")

    providers = [
        ("ollama", OllamaProvider()),
        ("openai", OpenAIProvider()),
        ("anthropic", AnthropicProvider()),
        ("gemini", GeminiProvider()),
        ("groq", GroqProvider()),
        ("deepseek", DeepSeekProvider()),
        ("qwen", QwenProvider()),
        ("mistral", MistralProvider()),
        ("openrouter", OpenRouterProvider()),
    ]

    for name, p in providers:
        # Test normalizer wrapper on dummy outputs
        out1 = normalize_content_chunk({"message": {"content": f"Hello from {name}"}})
        out2 = normalize_content_chunk({"files": [{"path": "App.tsx", "content": "export default App"}]})

        assert isinstance(out1, str), f"Provider {name} output 1 is not a string"
        assert isinstance(out2, str), f"Provider {name} output 2 is not a string"
        assert "[object Object]" not in out1, f"Provider {name} contains [object Object]"
        assert "[object Object]" not in out2, f"Provider {name} contains [object Object]"
        assert "### App.tsx" in out2, f"Provider {name} failed to format files block"
        print(f"  ✓ Provider [{name:<10}] ChatResponse contract verified")


def test_agent_roster_responses():
    print("\n► STEP 5 — VERIFYING ALL SPECIALIZED AGENTS RETURN STRING ChatResponse...")

    agents = [
        "Planner Agent", "Architect Agent", "Frontend Developer Agent",
        "Backend Developer Agent", "Database Engineer Agent", "API Engineer Agent",
        "DevOps Engineer Agent", "Security Engineer Agent", "QA Engineer Agent",
        "Documentation Writer Agent", "Deployment Agent"
    ]

    for agent_name in agents:
        dummy_agent_out = {"agent": agent_name, "content": f"Code generated by {agent_name}"}
        res = ensure_chat_response(dummy_agent_out)
        assert isinstance(res, str), f"Agent {agent_name} did not return a string"
        assert "[object Object]" not in res, f"Agent {agent_name} contains [object Object]"
        print(f"  ✓ Agent [{agent_name:<28}] ChatResponse contract verified")


def test_tool_outputs():
    print("\n► STEP 6 — VERIFYING ALL TOOL OUTPUTS ARE ChatResponse NORMALIZED...")

    tools = [
        CalculatorTool(),
        PythonExecutorTool(),
        ShellExecutorTool(),
        HttpRequestTool(),
    ]

    for tool in tools:
        dummy_tool_dict = {"tool": tool.name, "result": "OK", "data": [1, 2, 3]}
        norm_tool_out = ensure_chat_response(dummy_tool_dict)
        assert isinstance(norm_tool_out, str), f"Tool {tool.name} output is not string"
        assert "[object Object]" not in norm_tool_out, f"Tool {tool.name} contains [object Object]"
        print(f"  ✓ Tool [{tool.name:<20}] ChatResponse contract verified")


def test_project_generator_normalization():
    print("\n► STEP 7 — VERIFYING PROJECT GENERATOR { files: [] } TRANSFORM...")

    raw_project_obj = {
        "files": [
            {"path": "src/App.tsx", "content": 'export function App() { return <h1>Netflix Clone</h1>; }'},
            {"path": "src/index.css", "content": "body { background: black; }"},
        ]
    }

    transformed = normalize_content_chunk(raw_project_obj)
    assert isinstance(transformed, str), "Transformed project generator output is not string"
    assert "### src/App.tsx" in transformed, "Missing Markdown header for App.tsx"
    assert "```tsx" in transformed, "Missing tsx code block for App.tsx"
    assert "### src/index.css" in transformed, "Missing Markdown header for index.css"
    assert "[object Object]" not in transformed, "Project generator output contains [object Object]"

    print("  ✓ Project Generator { files: [] } payload successfully transformed into Markdown code blocks")


if __name__ == "__main__":
    print("=" * 80)
    print(" END-TO-END PROVIDER, AGENT, TOOL & PROJECT GENERATOR AUDIT")
    print("=" * 80)
    test_provider_chat_response_types()
    test_agent_roster_responses()
    test_tool_outputs()
    test_project_generator_normalization()
    print("\n" + "=" * 80)
    print(" ALL END-TO-END AUDIT SUITES PASSED! ZERO [object Object] DETECTED.")
    print("=" * 80 + "\n")
