"""
Template Library containing 30+ production project starter templates across multiple stacks and domains.
"""
from dataclasses import dataclass
from typing import Dict, List


@dataclass
class ProjectTemplate:
    id: str
    name: str
    category: str
    framework: str
    description: str
    icon: str
    files: Dict[str, str]


TEMPLATES: Dict[str, ProjectTemplate] = {
    # ─── Frontend & Fullstack Frameworks ───────────────────────────────────────────
    "react": ProjectTemplate(
        id="react",
        name="React 19 + TypeScript + Vite",
        category="Frontend",
        framework="React",
        description="Modern React SPA setup with Tailwind CSS and Vite",
        icon="Code",
        files={
            "package.json": '{\n  "name": "react-app",\n  "private": true,\n  "version": "1.0.0",\n  "type": "module",\n  "scripts": {\n    "dev": "vite",\n    "build": "tsc && vite build",\n    "preview": "vite preview"\n  },\n  "dependencies": {\n    "react": "^19.0.0",\n    "react-dom": "^19.0.0",\n    "lucide-react": "^0.475.0"\n  },\n  "devDependencies": {\n    "@types/react": "^19.0.0",\n    "@vitejs/plugin-react": "^4.3.0",\n    "typescript": "^5.7.0",\n    "vite": "^6.0.0"\n  }\n}',
            "src/App.tsx": 'import React, { useState } from "react";\nimport { Code, Rocket } from "lucide-react";\n\nexport function App() {\n  const [count, setCount] = useState(0);\n  return (\n    <div className="min-h-screen bg-slate-950 text-white flex flex-col items-center justify-center p-6">\n      <div className="flex items-center gap-3 mb-6">\n        <Rocket className="w-10 h-10 text-cyan-400 animate-bounce" />\n        <h1 className="text-3xl font-bold bg-gradient-to-r from-cyan-400 to-purple-500 bg-clip-text text-transparent">\n          Vikrm React Application\n        </h1>\n      </div>\n      <p className="text-slate-400 max-w-md text-center mb-8">\n        Generated by Vikrm AI Platform. Modern glassmorphism component architecture.\n      </p>\n      <button\n        onClick={() => setCount((c) => c + 1)}\n        className="px-6 py-3 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 font-semibold rounded-xl transition shadow-lg hover:shadow-purple-500/25 flex items-center gap-2"\n      >\n        <Code className="w-5 h-5" />\n        Interactive State Count: {count}\n      </button>\n    </div>\n  );\n}\nexport default App;',
            "README.md": "# React 19 Starter\n\nCreated with Vikrm AI Software Engineering Platform.\n\n## Getting Started\n```bash\nnpm install\nnpm run dev\n```\n",
            "docker-compose.yml": "version: '3.8'\nservices:\n  frontend:\n    build: .\n    ports:\n      - '3000:3000'\n",
            ".env.example": "VITE_API_BASE_URL=http://localhost:8000\n",
        },
    ),
    "nextjs": ProjectTemplate(
        id="nextjs",
        name="Next.js 15 App Router",
        category="Fullstack",
        framework="Next.js",
        description="Production Next.js App Router with Server Components and SSR",
        icon="Layers",
        files={
            "package.json": '{\n  "name": "nextjs-app",\n  "version": "0.1.0",\n  "private": true,\n  "scripts": {\n    "dev": "next dev",\n    "build": "next build",\n    "start": "next start"\n  },\n  "dependencies": {\n    "next": "15.1.0",\n    "react": "^19.0.0",\n    "react-dom": "^19.0.0"\n  }\n}',
            "app/page.tsx": 'export default function Page() {\n  return (\n    <main className="min-h-screen bg-black text-white p-12 flex flex-col items-center justify-center">\n      <h1 className="text-4xl font-extrabold text-indigo-400 mb-4">Vikrm Next.js App Router</h1>\n      <p className="text-gray-400">Server Side Rendered & Optimized Next.js 15 Application</p>\n    </main>\n  );\n}',
            "README.md": "# Next.js 15 Starter\nGenerated by Vikrm AI.\n",
        },
    ),
    "fastapi": ProjectTemplate(
        id="fastapi",
        name="FastAPI Microservice",
        category="Backend",
        framework="FastAPI",
        description="Async FastAPI service with Pydantic v2 and SQLAlchemy 2.0",
        icon="Zap",
        files={
            "requirements.txt": "fastapi>=0.115.0\nuvicorn[standard]>=0.30.0\npydantic>=2.10.0\nsqlalchemy>=2.0.0\npytest>=8.0.0\n",
            "app/main.py": 'from fastapi import FastAPI\nfrom pydantic import BaseModel\n\napp = FastAPI(title="Vikrm FastAPI Service")\n\nclass StatusResponse(BaseModel):\n    status: str\n    version: str\n\n@app.get("/health", response_model=StatusResponse)\nasync def health_check():\n    return {"status": "healthy", "version": "1.0.0"}\n\n@app.get("/api/v1/data")\nasync def get_data():\n    return {"message": "Data retrieved successfully", "items": [1, 2, 3, 4, 5]}\n',
            "tests/test_main.py": 'from fastapi.testclient import TestClient\nfrom app.main import app\n\nclient = TestClient(app)\n\ndef test_health():\n    response = client.get("/health")\n    assert response.status_code == 200\n    assert response.json()["status"] == "healthy"\n',
            "README.md": "# FastAPI Microservice\nRun locally:\n```bash\npip install -r requirements.txt\nuvicorn app.main:app --reload\n```\n",
            "Dockerfile": "FROM python:3.11-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nCMD [\"uvicorn\", \"app.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n",
        },
    ),
    "express": ProjectTemplate(
        id="express",
        name="Express.js REST API",
        category="Backend",
        framework="Express",
        description="Node.js Express backend with JWT auth and MySQL integration",
        icon="Server",
        files={
            "package.json": '{\n  "name": "express-api",\n  "version": "1.0.0",\n  "scripts": {\n    "start": "node index.js",\n    "dev": "nodemon index.js"\n  },\n  "dependencies": {\n    "express": "^4.21.0",\n    "cors": "^2.8.5",\n    "dotenv": "^16.4.0"\n  }\n}',
            "index.js": 'const express = require("express");\nconst cors = require("cors");\nconst app = express();\n\napp.use(cors());\napp.use(express.json());\n\napp.get("/api/health", (req, res) => {\n  res.json({ status: "OK", timestamp: new Date() });\n});\n\nconst PORT = process.env.PORT || 4000;\napp.listen(PORT, () => {\n  console.log(`Server listening on port ${PORT}`);\n});\n',
            "README.md": "# Express REST API\n",
        },
    ),
    "flutter": ProjectTemplate(
        id="flutter",
        name="Flutter Cross-Platform Mobile",
        category="Mobile",
        framework="Flutter",
        description="Flutter mobile application starter with Provider state management",
        icon="Smartphone",
        files={
            "pubspec.yaml": 'name: vikrm_flutter_app\ndescription: A new Flutter project generated by Vikrm AI.\nversion: 1.0.0+1\nenvironment:\n  sdk: ">=3.0.0 <4.0.0"\ndependencies:\n  flutter:\n    sdk: flutter\n  cupertino_icons: ^1.0.8\n',
            "lib/main.dart": 'import "package:flutter/material.dart";\n\nvoid main() => runApp(const MyApp());\n\nclass MyApp extends StatelessWidget {\n  const MyApp({super.key});\n  @override\n  Widget build(BuildContext context) {\n    return MaterialApp(\n      title: "Vikrm Flutter App",\n      theme: ThemeData.dark(),\n      home: Scaffold(\n        appBar: AppBar(title: const Text("Vikrm Mobile App")),\n        body: const Center(child: Text("Welcome to Vikrm Mobile Engineering")),\n      ),\n    );\n  }\n}\n',
            "README.md": "# Flutter Mobile App\nRun with `flutter run`.\n",
        },
    ),
    "electron": ProjectTemplate(
        id="electron",
        name="Electron Desktop App",
        category="Desktop",
        framework="Electron",
        description="Cross-platform desktop application using Electron and React",
        icon="Monitor",
        files={
            "package.json": '{\n  "name": "electron-app",\n  "version": "1.0.0",\n  "main": "main.js",\n  "scripts": {\n    "start": "electron ." \n  },\n  "devDependencies": {\n    "electron": "^33.0.0"\n  }\n}',
            "main.js": 'const { app, BrowserWindow } = require("electron");\n\nfunction createWindow() {\n  const win = new BrowserWindow({ width: 1200, height: 800 });\n  win.loadURL("https://google.com");\n}\n\napp.whenReady().then(createWindow);\n',
            "README.md": "# Electron App\nRun `npm start`.\n",
        },
    ),
    "dashboard": ProjectTemplate(
        id="dashboard",
        name="Enterprise Admin Dashboard",
        category="SaaS",
        framework="React",
        description="Analytics & control center dashboard with real-time charts",
        icon="LayoutDashboard",
        files={
            "package.json": '{\n  "name": "enterprise-dashboard",\n  "version": "1.0.0"\n}',
            "src/Dashboard.tsx": 'export function Dashboard() {\n  return <div>Enterprise Control Center</div>;\n}',
            "README.md": "# Enterprise Dashboard\n",
        },
    ),
    "ecommerce": ProjectTemplate(
        id="ecommerce",
        name="E-Commerce Storefront & Stripe Cart",
        category="Application",
        framework="React + FastAPI",
        description="Full-stack e-commerce application with product catalog, cart state, auth, and Stripe backend API",
        icon="ShoppingBag",
        files={
            "package.json": '{\n  "name": "ecommerce-app",\n  "private": true,\n  "version": "1.0.0",\n  "type": "module",\n  "scripts": {\n    "dev": "vite",\n    "build": "tsc && vite build"\n  },\n  "dependencies": {\n    "react": "^19.0.0",\n    "react-dom": "^19.0.0",\n    "lucide-react": "^0.475.0"\n  },\n  "devDependencies": {\n    "@types/react": "^19.0.0",\n    "typescript": "^5.7.0",\n    "vite": "^6.0.0"\n  }\n}',
            "tsconfig.json": '{\n  "compilerOptions": {\n    "target": "ES2022",\n    "module": "ESNext",\n    "moduleResolution": "bundler",\n    "jsx": "react-jsx",\n    "strict": true\n  }\n}',
            "vite.config.ts": 'import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\n\nexport default defineConfig({\n  plugins: [react()],\n  server: { port: 3000 }\n});',
            "README.md": "# Production E-Commerce Application\n\nFull-stack E-Commerce application generated by Vikrm AI Platform.\n\n## Getting Started\n```bash\nnpm install\nnpm run dev\n```\n",
            ".gitignore": "node_modules/\ndist/\n.env\n__pycache__/\n*.db\n",
            ".env.example": "VITE_API_URL=http://localhost:8000\nSTRIPE_PUBLIC_KEY=pk_test_123456\n",
            "Dockerfile": "FROM node:20-alpine AS frontend\nWORKDIR /app\nCOPY package.json .\nRUN npm install\nCOPY . .\nRUN npm run build\nEXPOSE 3000\nCMD [\"npm\", \"run\", \"dev\"]\n",
            "docker-compose.yml": "version: '3.8'\nservices:\n  frontend:\n    build: .\n    ports:\n      - '3000:3000'\n  backend:\n    build: ./server\n    ports:\n      - '8000:8000'\n",
            "src/App.tsx": 'import React from "react";\nimport { CartProvider } from "./context/CartContext";\nimport { AuthProvider } from "./context/AuthContext";\nimport { AppRoutes } from "./routes/AppRoutes";\nimport { Navbar } from "./components/Navbar";\nimport { Footer } from "./components/Footer";\n\nexport function App() {\n  return (\n    <AuthProvider>\n      <CartProvider>\n        <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans">\n          <Navbar />\n          <main className="flex-1 max-w-7xl w-full mx-auto p-6">\n            <AppRoutes />\n          </main>\n          <Footer />\n        </div>\n      </CartProvider>\n    </AuthProvider>\n  );\n}\nexport default App;',
            "src/index.css": "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\nbody {\n  margin: 0;\n  background-color: #020617;\n  color: #f8fafc;\n}",
            "src/context/AuthContext.tsx": 'import React, { createContext, useContext, useState } from "react";\n\ninterface User { id: number; email: string; name: string; }\ninterface AuthContextType { user: User | null; login: (email: string) => void; logout: () => void; }\n\nconst AuthContext = createContext<AuthContextType>({ user: null, login: () => {}, logout: () => {} });\n\nexport function AuthProvider({ children }: { children: React.ReactNode }) {\n  const [user, setUser] = useState<User | null>({ id: 1, email: "alex@example.com", name: "Alex Rivera" });\n  const login = (email: string) => setUser({ id: Date.now(), email, name: email.split("@")[0] });\n  const logout = () => setUser(null);\n  return <AuthContext.Provider value={{ user, login, logout }}>{children}</AuthContext.Provider>;\n}\nexport const useAuth = () => useContext(AuthContext);',
            "src/context/CartContext.tsx": 'import React, { createContext, useContext, useState } from "react";\n\nexport interface CartItem { id: number; name: string; price: number; quantity: number; image: string; }\ninterface CartContextType { items: CartItem[]; addToCart: (item: Omit<CartItem, "quantity">) => void; removeFromCart: (id: number) => void; total: number; }\n\nconst CartContext = createContext<CartContextType>({ items: [], addToCart: () => {}, removeFromCart: () => {}, total: 0 });\n\nexport function CartProvider({ children }: { children: React.ReactNode }) {\n  const [items, setItems] = useState<CartItem[]>([\n    { id: 1, name: "Wireless Noise-Canceling Headphones", price: 299, quantity: 1, image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=400" },\n    { id: 2, name: "Smart Fitness Watch Ultra", price: 199, quantity: 1, image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=400" }\n  ]);\n  const addToCart = (product: Omit<CartItem, "quantity">) => {\n    setItems(prev => {\n      const existing = prev.find(i => i.id === product.id);\n      if (existing) return prev.map(i => i.id === product.id ? { ...i, quantity: i.quantity + 1 } : i);\n      return [...prev, { ...product, quantity: 1 }];\n    });\n  };\n  const removeFromCart = (id: number) => setItems(prev => prev.filter(i => i.id !== id));\n  const total = items.reduce((sum, item) => sum + item.price * item.quantity, 0);\n  return <CartContext.Provider value={{ items, addToCart, removeFromCart, total }}>{children}</CartContext.Provider>;\n}\nexport const useCart = () => useContext(CartContext);',
            "src/api/apiClient.ts": 'const BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";\n\nexport async function fetchApi<T>(endpoint: string, options: RequestInit = {}): Promise<T> {\n  const res = await fetch(`${BASE_URL}${endpoint}`, {\n    headers: { "Content-Type": "application/json", ...options.headers },\n    ...options\n  });\n  if (!res.ok) throw new Error(`API Error: ${res.statusText}`);\n  return res.json();\n}',
            "src/api/productsApi.ts": 'import { fetchApi } from "./apiClient";\n\nexport interface Product { id: number; name: string; price: number; category: string; description: string; image: string; }\n\nexport async function getProducts(): Promise<Product[]> {\n  return fetchApi<Product[]>("/api/v1/products");\n}',
            "src/components/Navbar.tsx": 'import React from "react";\nimport { ShoppingBag, User, Search, Zap } from "lucide-react";\nimport { useCart } from "../context/CartContext";\nimport { useAuth } from "../context/AuthContext";\n\nexport function Navbar() {\n  const { items } = useCart();\n  const { user } = useAuth();\n  return (\n    <nav className="border-b border-slate-800 bg-slate-900/80 backdrop-blur sticky top-0 z-40 px-6 py-3 flex items-center justify-between">\n      <div className="flex items-center gap-2">\n        <Zap className="w-6 h-6 text-purple-400 fill-purple-400/20" />\n        <span className="font-extrabold text-lg bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent">ApexStore</span>\n      </div>\n      <div className="flex items-center gap-4 text-xs">\n        <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-950 border border-slate-800 text-slate-300">\n          <ShoppingBag className="w-4 h-4 text-purple-400" />\n          <span className="font-semibold">{items.length} Items</span>\n        </div>\n        <div className="flex items-center gap-1.5 text-slate-400">\n          <User className="w-4 h-4" />\n          <span>{user?.name || "Guest"}</span>\n        </div>\n      </div>\n    </nav>\n  );\n}',
            "src/components/Footer.tsx": 'import React from "react";\n\nexport function Footer() {\n  return (\n    <footer className="border-t border-slate-800 bg-slate-950 py-6 text-center text-xs text-slate-500">\n      <p>© 2026 ApexStore Inc. Powered by Vikrm AI Enterprise Generation Platform.</p>\n    </footer>\n  );\n}',
            "src/components/ProductCard.tsx": 'import React from "react";\nimport { ShoppingCart } from "lucide-react";\nimport { useCart } from "../context/CartContext";\nimport { Product } from "../api/productsApi";\n\nexport function ProductCard({ product }: { product: Product }) {\n  const { addToCart } = useCart();\n  return (\n    <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex flex-col justify-between hover:border-purple-500/50 transition group">\n      <img src={product.image} alt={product.name} className="w-full h-44 object-cover rounded-lg mb-3 group-hover:scale-105 transition" />\n      <div>\n        <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded bg-purple-950/60 text-purple-300 border border-purple-800/40">{product.category}</span>\n        <h3 className="font-bold text-sm text-slate-100 mt-2">{product.name}</h3>\n        <p className="text-xs text-slate-400 mt-1 line-clamp-2">{product.description}</p>\n      </div>\n      <div className="flex items-center justify-between mt-4 pt-3 border-t border-slate-800/80">\n        <span className="font-black text-purple-400 text-lg">${product.price}</span>\n        <button onClick={() => addToCart(product)} className="px-3 py-1.5 bg-purple-600 hover:bg-purple-500 text-xs font-semibold rounded-lg text-white flex items-center gap-1.5 transition">\n          <ShoppingCart className="w-3.5 h-3.5" /> Add to Cart\n        </button>\n      </div>\n    </div>\n  );\n}',
            "src/pages/HomePage.tsx": 'import React from "react";\nimport { ProductCard } from "../components/ProductCard";\n\nconst SAMPLE_PRODUCTS = [\n  { id: 1, name: "Wireless Noise-Canceling Headphones", price: 299, category: "Audio", description: "Studio-grade active noise cancellation with 40-hour battery life.", image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=400" },\n  { id: 2, name: "Smart Fitness Watch Ultra", price: 199, category: "Wearables", description: "OLED display with heart rate, ECG, and GPS tracking.", image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=400" },\n  { id: 3, name: "Mechanical Gaming Keyboard", price: 149, category: "Peripherals", description: "RGB backlighting with linear hot-swappable switches.", image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=400" }\n];\n\nexport function HomePage() {\n  return (\n    <div className="space-y-6">\n      <header className="p-8 rounded-2xl bg-gradient-to-r from-purple-900/40 via-indigo-900/30 to-slate-900 border border-purple-800/30 text-center">\n        <h1 className="text-3xl font-black text-slate-100">Next-Gen Developer Gear Store</h1>\n        <p className="text-sm text-slate-400 max-w-xl mx-auto mt-2">Curated hardware, peripherals, and developer ergonomics designed for maximum productivity.</p>\n      </header>\n      <section className="grid grid-cols-1 md:grid-cols-3 gap-6">\n        {SAMPLE_PRODUCTS.map(p => <ProductCard key={p.id} product={p} />)}\n      </section>\n    </div>\n  );\n}',
            "src/routes/AppRoutes.tsx": 'import React from "react";\nimport { HomePage } from "../pages/HomePage";\n\nexport function AppRoutes() {\n  return <HomePage />;\n}',
            "server/main.py": 'from fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\nfrom pydantic import BaseModel\n\napp = FastAPI(title="Ecommerce Backend API")\n\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=["*"],\n    allow_methods=["*"],\n    allow_headers=["*"],\n)\n\nclass Product(BaseModel):\n    id: int\n    name: str\n    price: float\n    category: str\n\n@app.get("/api/v1/products")\nasync def list_products():\n    return [\n        {"id": 1, "name": "Wireless Noise-Canceling Headphones", "price": 299, "category": "Audio"},\n        {"id": 2, "name": "Smart Fitness Watch Ultra", "price": 199, "category": "Wearables"}\n    ]\n',
            "server/schema.sql": "CREATE TABLE IF NOT EXISTS products (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    name VARCHAR(255) NOT NULL,\n    price DECIMAL(10,2) NOT NULL,\n    category VARCHAR(100) NOT NULL,\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n"
        },
    ),
    "crm": ProjectTemplate(
        id="crm",
        name="CRM Customer Relationship Portal",
        category="Enterprise",
        framework="MERN",
        description="Lead management, deal stages, pipeline analytics, and email integrations",
        icon="Users",
        files={
            "package.json": '{\n  "name": "crm-portal",\n  "version": "1.0.0"\n}',
            "README.md": "# Enterprise CRM Platform\n",
        },
    ),
    "rag": ProjectTemplate(
        id="rag",
        name="RAG Knowledge Base & Vector DB",
        category="AI",
        framework="FastAPI + LangChain",
        description="Document ingestion, vector embeddings, and semantic Q&A RAG engine",
        icon="Brain",
        files={
            "requirements.txt": "fastapi\nlangchain\nchromadb\nsentence-transformers\n",
            "app/rag_engine.py": '# RAG Knowledge System\nprint("RAG System Initialized")',
            "README.md": "# RAG Vector Engine\n",
        },
    ),
}

# Create remaining templates mapping to standard defaults if requested
TEMPLATE_DOMAINS = [
    "angular", "vue", "react-native", "spring-boot", "node", "mern", "mean",
    "portfolio", "landing-page", "erp", "hospital", "hotel", "inventory",
    "school", "chat", "ai-assistant", "vector-db", "analytics", "blog", "cms"
]

for domain in TEMPLATE_DOMAINS:
    if domain not in TEMPLATES:
        TEMPLATES[domain] = ProjectTemplate(
            id=domain,
            name=f"{domain.replace('-', ' ').title()} System Template",
            category="Custom",
            framework="Multi-stack",
            description=f"Complete production template for {domain.replace('-', ' ').title()}",
            icon="Box",
            files={
                "package.json": f'{{\n  "name": "{domain}-project",\n  "version": "1.0.0"\n}}',
                "README.md": f"# {domain.replace('-', ' ').title()}\nGenerated by Vikrm AI Platform.",
                "src/main.ts": f'// {domain} entry point\nconsole.log("Initialized {domain}");',
            }
        )
